blindspot/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main_app.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
  path('', views.home, name='home'),
  path('about/', views.about, name='about'),
  path('cars/', views.cars_index, name='index'),
  path('cars/<int:car_id>/', views.cars_detail, name='detail'),
  path('cars/search_cars', views.search_cars, name='search_cars'),
  path('cars/create/', views.CarCreate.as_view(), name='cars_create'),
  path('cars/<int:pk>/update/', views.CarUpdate.as_view(), name='cars_update'),
  path('cars/<int:pk>/delete/', views.CarDelete.as_view(), name='cars_delete'),
  path('cars/<int:car_id>/add_comment/', views.add_comment, name='add_comment'),
  path('cars/<int:car_id>/add_review/', views.add_review, name='add_review'),
  path('comments/<int:pk>/update', views.CommentUpdate.as_view(), name='comment_update'),
  path('comments/<int:pk>/delete', views.CommentDelete.as_view(), name='comment_delete'),
  path('cars/<int:car_id>/add_photo/', views.add_photo, name='add_photo'),
  path('reviews/', views.ReviewList.as_view(), name='reviews_index'),
  path('reviews/<int:pk>/', views.ReviewDetail.as_view(), name='reviews_detail'),
  path('reviews/create/', views.ReviewCreate.as_view(), name='reviews_create'),
  path('reviews/<int:pk>/update/', views.ReviewUpdate.as_view(), name='reviews_update'),
  path('reviews/<int:pk>/delete/', views.ReviewDelete.as_view(), name='reviews_delete'),
  path('accounts/signup/', views.signup, name='signup'),
]

main_app/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date

# Create your models here

class Car(models.Model):
  make = models.CharField(max_length=50)
  model = models.CharField(max_length=50)
  year = models.IntegerField()
  engine = models.CharField(max_length=50)
  mileage = models.IntegerField()
  user = models.ForeignKey(User, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.make} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'car_id': self.id})

class Review(models.Model):
  description = models.CharField(max_length=1500)
  rating = models.CharField(max_length=10)
  date = models.DateField(auto_now_add=True)
  car = models.ForeignKey(Car, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.make} ({self.id})'

  class Meta:
    ordering = ['-date']

  def get_absolute_url(self):
    return reverse('reviews_detail', kwargs={'review_id': self.id})

class Comment(models.Model):
  description = models.CharField(max_length=150)
  date = models.DateField(auto_now_add=True)
  car = models.ForeignKey(Car, on_delete=models.CASCADE)

  def __str__(self):
    return f'{self.make} ({self.id})'

  def get_absolute_url(self):
    return reverse('detail', kwargs={'comment_id': self.id})

  class Meta:
    ordering = ['-date']

class Photo(models.Model):
    url = models.CharField(max_length=200)
    car = models.ForeignKey(Car, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for car_id: {self.car_id} @{self.url}"

main_app/forms.py
from django.forms import ModelForm
from .models import Comment, Review

class CommentForm(ModelForm):
  class Meta:
    model = Comment
    fields = ['description']

class ReviewForm(ModelForm):
  class Meta:
    model = Review
    fields = ['description', 'rating']

main_app/views.py
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import os
import uuid
import boto3
from .models import Car, Review, Photo, Comment
from .forms import CommentForm, ReviewForm

# Define the home view


def home(request):
  return render(request, 'home.html')


def about(request):
  return render(request, 'about.html')

@login_required
def cars_index(request):
    cars = Car.objects.all()
    return render(request, 'cars/index.html', {'cars': cars})

def cars_detail(request, car_id):
  car = Car.objects.get(id=car_id)
  comment_form = CommentForm()
  review_form = ReviewForm()
  id_list = car.review_set.all().values_list('id')
  return render(request, 'cars/detail.html', {
    'car': car,
    'comment_form': comment_form,
    'review_form': review_form,
    'reviews': id_list,
  })


class CarCreate(LoginRequiredMixin, CreateView):
  model = Car
  fields = ['make', 'model', 'year', 'engine', 'mileage']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class CarUpdate(LoginRequiredMixin, UpdateView):
  model = Car
  fields = ['make', 'model', 'year', 'engine', 'mileage']


class CarDelete(LoginRequiredMixin, DeleteView):
  model = Car
  success_url = '/cars/'


@login_required
def add_comment(request, car_id):
  form = CommentForm(request.POST)
  if form.is_valid():
    new_comment = form.save(commit=False)
    new_comment.car_id = car_id
    new_comment.save()
  return redirect('detail', car_id=car_id)


class CommentCreate(LoginRequiredMixin, CreateView):
  model = Comment
  fields = ['description']

  def form_valid(self, form):
    form.instance.user = self.request.user
    return super().form_valid(form)


class CommentUpdate(LoginRequiredMixin, UpdateView):
  model = Comment
  fields = ['description']
  success_url = '/cars/'


class CommentDelete(LoginRequiredMixin, DeleteView):
  model = Comment
  slug_field = 'product_slug'
  success_url = '/cars/'


@login_required
def add_review(request, car_id):
  form = ReviewForm(request.POST)
  if form.is_valid():
    new_review = form.save(commit=False)
    new_review.car_id = car_id
    new_review.save()
  return redirect('detail', car_id=car_id)


class ReviewList(LoginRequiredMixin, ListView):
  model = Review


class ReviewDetail(LoginRequiredMixin, DetailView):
  model = Review


class ReviewCreate(LoginRequiredMixin, CreateView):
  model = Review
  fields = '__all__'


class ReviewUpdate(LoginRequiredMixin, UpdateView):
  model = Review
  fields = ['description']


class ReviewDelete(LoginRequiredMixin, DeleteView):
  model = Review
  success_url = '/reviews/'


@login_required
def add_photo(request, car_id):
    photo_file = request.FILES.get('photo-file', None)
    if photo_file:
        s3 = boto3.client('s3')
        key = uuid.uuid4().hex[:6] + \
                         photo_file.name[photo_file.name.rfind('.'):]
        try:
            bucket = os.environ['S3_BUCKET']
            s3.upload_fileobj(photo_file, bucket, key)
            url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
            Photo.objects.create(url=url, car_id=car_id)
        except Exception as e:
            print('An error occurred uploading file to S3')
            print(e)
    return redirect('detail', car_id=car_id)


def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)


def search_cars(request):
	if request.method == "POST":
		searched = request.POST['searched']
		cars = Car.objects.filter(make__contains=searched)
	
		return render(request, 
		'cars/search_cars.html', 
		{'searched':searched,
		'cars':cars})
	else:
		return render(request, 
		'cars/search_cars.html', 
		{})

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}

<div class="formMargin">
  <h1 class="title"><img src="https://i.imgur.com/BRhevDE.png" alt="car" class="car"> About Blindspot</h1>
  <hr>
  <h4 class="aboutUs">Here at Blindspot, we want our users to have the best rated knowledge before going into the market for that big car purchase.</h4>
  <h4 class="aboutUs">Thank you for using Blindspot! ❤️</h4>
  <br>
  <h4>Meet the Team</h4>

  <table class="striped">
    <thead>
      <tr>
        <th class="center"><img src="https://i.imgur.com/0GDb2VL.png" alt="Jordan-Christopher"></th>
        <th class="center"><img src="https://i.imgur.com/8r3Nbgj.png" alt="Tesh Deo"></th>
        <th class="center"><img src="https://i.imgur.com/DM8H1UF.png" alt="Yi Li"></th>
      </tr>
    </thead>
    <tbody>
      <tr class="about">
        <td class="center">
          <p>Jordan-Christopher Garcia</p>
          <a href="https://www.github.com/jctgarcia20" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/github.svg" width="32" height="32" /></a>
        </td>
        <td class="center">
          <p>Tesh Deo</p>
          <a href="https://www.github.com/tesh510" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/github.svg" width="32" height="32" /></a>
        </td>
        <td class="center">
          <p>Yi Li</p>
          <a href="https://www.github.com/iam-yi" target="_blank" rel="noreferrer"><img src="https://raw.githubusercontent.com/danielcranney/readme-generator/main/public/icons/socials/github.svg" width="32" height="32" /></a>
        </td>
      </tr>
    </tbody>
  </table>
</div>



{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Blindspot</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,400,0,0" />
    <link rel="icon" type="image/png" href="/favicon.png" />
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
    <link rel="icon" type="image/png" href="https://i.imgur.com/EL2mVW9.png" />
</head>

<body>
    <header class="navbar-fixed">
        <nav>
            <div>
                <ul>
                    <li><a href="/" class="brand-logo center black-text">&nbsp;&nbsp;Blindspot</a></li>
                </ul>
                <div>
                    <ul class="left hide-on-med-and-down">
                        <form class="input-field" method=POST action="{% url 'search_cars' %}">
                            {% csrf_token %}
                            <div id="searchBar">
                                <input class="form-control me-2" type="search" placeholder="Search Cars" aria-label="Search" name="searched">
                                <button id="searchBtn" class="btn white black-text" type="submit"><span class="material-symbols-outlined">search</span></button>
                            </div>
                        </form>
                    </ul>
                </div>
                <ul class="right hide-on-med-and-down">
                    <li><a href="{% url 'about' %}" class="black-text">About</a></li>
                    {% if user.is_authenticated %}
                    <li><a href="{% url 'cars_create' %}" class="black-text">Add a Car</a></li>
                    <li><a href="{% url 'index' %}" class="black-text">All Car Reviews</a></li>
                    <div class="right hide-on-med-and-down">
                        <li><a href="{% url 'logout' %}" class="black-text">Log Out</a></li>
                        {% else %}
                        <li><a href="{% url 'signup' %}" class="black-text">Sign Up</a></li>
                        <li><a href="{% url 'login' %}" class="black-text">Log In</a></li>
                    </div>
                    {% endif %}
                </ul>
                </ul>
            </div>
        </nav>
    </header>
    <main>
        {% block content %}
        {% endblock %}
    </main>
    <footer class="page-footer grey darken-3" id="footer">
        <div class="center-align" id="footerTxt">All Rights Reserved, &copy; 2022 Blindspot &nbsp;</div>
    </footer>
</body>

</html>

main_app/templates/cars/detail.html
{% extends 'base.html' %}
{% block content %}

<div class="formMargin">
  <h1 class="title">Vehicle Details</h1>
  <div class="center">
    {% for photo in car.photo_set.all %}
    <img class="responsive-img card-panel" src="{{photo.url}}">
    {% empty %}
    <div class="card-panel teal-text center-align">No Photos Uploaded</div>
    {% endfor %}
    <form action="{% url 'add_photo' car.id %}" enctype="multipart/form-data" method="POST" alt="Car Photo"
      class="card-panel" class="align-left">
      {% csrf_token %}
      <input type="file" name="photo-file">
      <input type="submit" class="btn  light-blue lighten-1" value="Upload Photo">
    </form>
  </div>
  <div class="card col s7 push-s5">
    <div class="card-content">
      <span class="card-title">{{ car.name }}</span>
      <p>Make: {{ car.make }}</p>
      <p>Model: {{ car.model }} </p>
      <p>Year: {{ car.year }}</p>
      <p>Engine: {{ car.engine }}</p>
      <p>Mileage: {{ car.mileage }}</p>
    </div>
    <div class="card-action">
      <a href="{% url 'cars_update' car.id %}">Edit</a>
      <a href="{% url 'cars_delete' car.id %}">Delete</a>
    </div>
  </div>
  </div>
</div>

<div class="formMargin">
  <div class="col s6">
    <h4>Reviews</h4>
    <div class="col s6">
      <form action="{% url 'add_review' car.id %}" method="POST">
        {% csrf_token %}
        {{ review_form.as_p }}
        <input type="submit" class="btn  light-blue lighten-1" value="Add a Review">
      </form>
      <br>
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Reviews</th>
            <th>Rating</th>
          </tr>
        </thead>
        <tbody>
          {% for review in car.review_set.all %}
          <tr>
            <td>{{ review.date }}</td>
            <td>{{ review.description }}</td>
            <td>{{ review.rating }}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <br>
    <br>
    <div class="col s6">
      <h4>Questions</h4>
      <form action="{% url 'add_comment' car.id %}" method="POST">
        {% csrf_token %}
        {{ comment_form.as_p }}
        <input type="submit" class="btn light-blue lighten-1" value="Ask a Question?">
      </form>
      <br>
      <table class="striped">
        <thead>
          <tr>
            <th>Date</th>
            <th>Questions</th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tbody>
          {% for comment in car.comment_set.all %}
          <tr>
            <td>{{comment.date}}</td>
            <td> {{ comment.description }}</td>
            <td><a href="{% url 'comment_update' comment.id %}">Edit</a></td>
            <td><a href="{% url 'comment_delete' comment.id %}">Delete</a></td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

<script>
  const dateEl = document.getElementById('id_date');
  M.Datepicker.init(dateEl, {
    format: 'yyyy-mm-dd',
    defaultDate: new Date(),
    setDefaultDate: true,
    autoClose: true
  });
  const selectEl = document.getElementById('id_comment');
  M.FormSelect.init(selectEl);

  document.addEventListener('DOMContentLoaded', function() {
    var elems = document.querySelectorAll('.dropdown-trigger');
    var instances = M.Dropdown.init(elems, options);
  });
</script>
{% endblock %}

main_app/templates/cars/index.html
{% extends 'base.html' %}
{% block content %}

<div class="formMargin">
  <h1 class="title">All Car Reviews</h1>

  {% for car in cars %}
  <div class="row">
    <div class="col s4">
      <a href="{% url 'detail' car.id %}">
      <div class="card" id="carCard">
          <div class="card-image">
            {% for photo in car.photo_set.all %}
            <img id="imageCard" src="{{ photo.url }}">
            {% endfor %}
          </div>
          <div class="card-content black-text">
            <p>Make: {{ car.make }}</p>
            <p>Model: {{ car.model }}</p>
            <p>Year: {{ car.year }}</p>
            <p>Engine: {{ car.engine }}</p>
            <p>Mileage: {{ car.mileage }}</p>
          </div>
        </a>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


{% endblock %}

main_app/templates/cars/search_cars.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
	{% if searched %}
	<h4>You Searched For "{{ searched }}"</h4>
	<br />

	{% for car in cars %}

	<div class="card">
		<div class="card-header">
			Car
		</div>
		<div class="card-body">
			<h5 class="card-title">{{ car }}</h5>
			<p class="card-text">
			<ul>
				{% if car.make %}
				<li>{{ car.make }}</li>
				{% endif %}

				{% if car.model %}
				<li>{{ car.model }}</li>
				{% endif %}

				{% if car.year %}
				<li>{{ car.year }}</li>
				{% endif %}
			</ul>
			</p>
		</div>
	</div>
	<br />
	{% endfor %}

	{% else %}
	<h1>Hey! You Forgot To Search For A Car...</h1>
	{% endif %}
</div>

	{% endblock %}

main_app/templates/home.html
{% extends 'base.html' %}
{% block content %}

<div id="homePage">
  <div id="containerHome">
    <video autoplay loop muted>
      <source src="https://i.imgur.com/2D2hFRj.mp4" type="video/mp4">
    </video>
    <div id="text-box">
      <h1 id="logo">BLINDSPOT</h1>
      <br>
      <a href="cars/create/" class="btn white-text" id="homeBtn">Add Car</a>
    </div>
  </div>
  
  <br>
  <h1 id="slogan">Quick. Easy. Reliable.</h1>
  <p id="mission">Here at Blindspot, we want our users to have the best rated knowledge before going into the market for that big car purchase.</p>

  <br>
  <h4 class="homeCaps">Get the information you need, when you need it.</h4>
  <img src="https://i.imgur.com/eEShxOd.jpg" class="homeImgs">
  <br>
  <h4 class="homeCaps">Read reviews from real people.</h4>
  <img src="https://i.imgur.com/1NAbDxk.jpg" class="homeImgs">
  <br>
  <h4 class="homeCaps">Save and organize.</h4>
  <img src="https://i.imgur.com/TBaN05z.jpg" class="homeImgs">

</div>

{% endblock %}

main_app/templates/main_app/car_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container center">
  <h1>Delete Car</h1>

  <h4>Are you sure you want to delete<span class="teal-text">{{ object.name }}</span>?</h4>

  <br>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn light-blue lighten-1">
    <br>
    <br>
    <a href="{% url 'detail' car.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/car_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  {% if object %}
  <h1 id="carAdd">Edit <span class="teal-text">{{ object.make }}</span></h1>
  {% else %}
  <h1 class="title" id="carAdd">Add Car</h1>
  {% endif %}

  <form action="" method="POST">
    {% csrf_token %}
    <div id="formsAddCar">
      <table>
        {{ form.as_table }}
      </table>
      <br>
      <input type="submit" value="Add Car to Blindspot" class="btn light-blue lighten-1">
    </div>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/comment_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
<div class="container center">
  <h1>Delete Comment</h1>

  <h4>Are you sure you want to delete<span class="teal-text">{{ object.name }}</span>?</h4>

  <br>
  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn light-blue lighten-1">
    <br>
    <br>
    <a href="{% url 'detail' comment.id %}">Cancel</a>
  </form>
</div>
{% endblock %}

main_app/templates/main_app/comment_form.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
  {% if object %}
    <h1>Edit Question<span class="teal-text">{{ object.name }}</span></h1>
  {% else %}
    <h1>Add Car</h1>
  {% endif %}

    <form action="" method="POST">
      {% csrf_token %}
      <table>
        {{ form.as_table }}
      </table>
      <br>
      <input type="submit" value="Resubmit" class="btn light-blue lighten-1">
    </form>
</div>
{% endblock %}

main_app/templates/main_app/review_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Review</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn light-blue lighten-1">
    <a href="{% url 'reviews_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/review_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Review Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ review.name }}</span>
      </div>
      <div class="card-action">
        <a href="{% url 'reviews_update' review.id %}">Edit</a>
        <a href="{% url 'reviews_delete' review.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/review_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Review</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <br>
    <input type="submit" value="Submit!" class="btn light-blue lighten-1">
  </form>
{% endblock %}

main_app/templates/main_app/review_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Review List</h1>

{% for review in review_list %}
  <a href="{% url 'reviews_detail' review.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ review.name }}</span>
        </div>
    </div>
  </a>
  <div class="col s6">{{ review.name }}</div>
{% endfor %}

{% endblock %}